version: '3'

services:

  web:
    build:
      context: .
      dockerfile: frontend.dockerfile
    command: yarn start
    ports:
      - 4200:4200
    volumes:
      - ./web:/app
    working_dir: /app

  deploy:
    build:
      context: .
      dockerfile: deploy.dockerfile
    entrypoint: /deploy/docker-entrypoint.sh
    env_file: deploy.env
    volumes:
      - ./deploy/.ssh:/root/.ssh
      - ./deploy:/deploy
      - ./web/dist:/app
    working_dir: /app
