version: '3'

services:

  web:
    build:
      context: .
      dockerfile: frontend.dockerfile
    command: yarn start
    ports:
      - 4200:4200
    volumes:
      - ./web:/app
    working_dir: /app
